apiVersion: apps/v1
kind: Deployment
metadata:
  name: delta-timelogger
  namespace: alpha
  labels:
    team: echannel
    retention: 6m
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: delta
  template:
    metadata:
      labels:
        deployment: delta
    spec:
      containers:
        - name: delta-timelogger-container
          image: vinukavinnath/spring-logger-t:v1
