apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: timelogger
  template:
    metadata:
      labels:
        deployment: timelogger
    spec:
      containers:
        - name: timelogger-container
          image: vinukavinnath/spring-logger-t:v1
