apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-timelogger
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: default
  template:
    metadata:
      labels:
        deployment: default
    spec:
      containers:
        - name: default-timelogger-container
          image: vinukavinnath/spring-logger-t:v1
