apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta-timelogger
  namespace: beta
  labels:
    team: bigdata
    retention: 3y
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: beta
  template:
    metadata:
      labels:
        deployment: beta
    spec:
      containers:
        - name: beta-timelogger-container
          image: vinukavinnath/spring-logger-t:v1
