apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-timelogger
  namespace: alpha
  labels:
    team: mcash
    retention: 6m
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: alpha
  template:
    metadata:
      labels:
        deployment: alpha
    spec:
      containers:
        - name: alpha-timelogger-container
          image: vinukavinnath/spring-logger-t:v1
